# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_labels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='labels',
            new_name='tags',
        ),
    ]
