# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field=b'height_field', null=True, upload_to=b'', width_field=b'width_field'),
        ),
    ]
