# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_auto_20160410_1646'),
        ('posts', '0004_auto_20160327_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='community',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='communities.Communities'),
        ),
    ]
