# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-13 21:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pictures',
            new_name='UserPictures',
        ),
    ]
