# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-14 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20160514_1633'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userLanguages',
            new_name='UserLanguage',
        ),
        migrations.RenameModel(
            old_name='UserPictures',
            new_name='UserPicture',
        ),
        migrations.RenameModel(
            old_name='userQualifications',
            new_name='UserQualification',
        ),
    ]
