# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-14 22:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0005_auto_20160514_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('picture', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=profiles.models.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='usergeneralinformation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userjob',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userlanguage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userpicture',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userqualification',
            name='user',
        ),
        migrations.DeleteModel(
            name='userGeneralInformation',
        ),
        migrations.DeleteModel(
            name='userJob',
        ),
        migrations.DeleteModel(
            name='UserLanguage',
        ),
        migrations.DeleteModel(
            name='UserPicture',
        ),
        migrations.DeleteModel(
            name='UserQualification',
        ),
    ]
