# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communities',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='communities',
            old_name='title',
            new_name='name',
        ),
    ]
