# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-12 17:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_auto_20170810_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communities',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
