# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-14 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_auto_20170812_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communities',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
