# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-14 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_auto_20170814_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communities',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
