# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-05-21 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '__first__'),
        ('communities', '0006_auto_20170814_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='communities',
            name='posts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
        ),
    ]
