# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
